# Generated by Django 5.1.3 on 2024-11-18 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0002_remove_leaf_amount_leaf_quantity"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="supplier_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.supplier",
            ),
        ),
    ]
