# Generated by Django 5.1.3 on 2025-01-01 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0003_medicine_supplier_name"),
        ("supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="box_size",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="expire_date",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="price",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="supplier_price",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="type",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="unit",
        ),
        migrations.CreateModel(
            name="MedicineBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=255)),
                ("expire_date", models.DateField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "supplier_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("status", models.CharField(default="1", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_by", models.IntegerField(blank=True, default=0, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("updated_by", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "admin_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "box_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.leaf",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.category",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="medicine.medicine",
                    ),
                ),
                (
                    "supplier_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.type",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.unit",
                    ),
                ),
            ],
            options={
                "db_table": "medicine_batch",
            },
        ),
    ]
