# Generated by Django 5.1.3 on 2025-01-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0004_remove_medicine_batch_remove_medicine_box_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaf",
            name="leaf_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
