# Generated by Django 5.1.3 on 2025-01-01 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0006_remove_leaf_leaf_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicinebatch",
            old_name="price",
            new_name="box_mrp",
        ),
        migrations.RenameField(
            model_name="medicinebatch",
            old_name="box_size",
            new_name="leaf",
        ),
    ]
