# Generated by Django 5.1.3 on 2025-01-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
        ("medicine", "0007_rename_price_medicinebatch_box_mrp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="medicine_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medicine.medicinebatch",
            ),
        ),
    ]
