# Generated by Django 5.1.3 on 2024-12-13 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="paymentgatewaysettings",
            table="sslcommerz",
        ),
    ]
